# Generated by Django 5.0.2 on 2024-03-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
