# Generated by Django 5.0.2 on 2024-03-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('blockno', models.CharField(max_length=10)),
                ('houseno', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=15)),
                ('job_address', models.TextField()),
                ('blood_grp', models.CharField(max_length=5)),
                ('vehicle_details', models.CharField(max_length=15)),
                ('pic', models.ImageField(default='default.png', upload_to='media/upload')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
